name:                colcise
version:             0.0.0.0
github:              "bas080/colcise"
license:             MIT
author:              "Bas Huis"
maintainer:          "example@example.com"
copyright:           "2018 Bas Huis"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/bas080/colcise#readme>

dependencies:
- base >= 4.7 && < 5
- regex-compat >= 0.9
- cmdargs >= 0.1
- text

library:
  source-dirs: src

executables:
  colcise:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - colcise

tests:
  colcise-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - colcise
